### ISSUE TITLE
Does i works with the latest game update?

### ISSUE THREAD

**Issue by SatanicScripter** [Ponita0/LickMyRunes#4]
Thanks

**Comment by Ponita0** [comment]
Actually i didnt test it for a while , but i suppose its working because i keep getting messages about users using it ( but wont work with vex till i update it )

**Comment by SatanicScripter** [comment]
Only with vex or other champ? Thanks a lot... i will download it :3

**Comment by Ponita0** [comment]
Yea its actually working , i asked my friends who totally using it instead of blitz and professor , and they told me that it's actually working perfectly 
But currently with no vex ( but dont worry , my friend . I will release an update soon to add vex's id to be able too pish vex's runes.) I hope you enjoy using my app ❤️

**Comment by Ponita0** [comment]
![IMG_20210910_083959](https://user-images.githubusercontent.com/34416796/132810970-07d4b499-d5e2-4d73-a23a-ff50ae070eb2.jpg)
Here's an example

**Comment by SatanicScripter** [comment]
And also, it does only runes or with builds. Thank ya :)

**Comment by SatanicScripter** [comment]
Oh excuse i close this, comment under this post

**Comment by SatanicScripter** [comment]
Oh excuse me i closed tha issue comment under this

**Comment by Ponita0** [comment]
Currently only runes
